name: FarmInventory
main: cc.ranmc.farm.Main
website: https://www.ranmc.cc/
description: '桃花源定制24k纯钛合金超级无敌终终终终极版专属作物菜单插件'
author: Ranica
version: Release 4.5
api-version: "1.21"
softdepend: [PlaceholderAPI,Ranmc]
folia-supported: true

permissions: 
  fm.user:
    default: true
    description: 'user only'

  fm.admin:
    default: op
    description: 'admin only'

commands:
  fm:
    description: fm
    usage: /<command>

  farm:
    description: farm
    usage: /<command>