name: FarmInventory
main: cc.ranmc.farm.inventory.Main
website: https://www.ranmc.cc/
description: '阿然定制24k纯钛合金超级无敌终终终终极版桃花源专属作物菜单插件'
author: Ranica
version: Beta 2.1
api-version: "1.20"
softdepend: [PlaceholderAPI]
folia-supported: true

permissions: 
  fm.user:
    default: true
    description: 'user only'

  fm.admin:
    default: op
    description: 'admin only'

commands:
  fm:
    description: fm
    usage: /<command>